/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  eigencloudSidebar: [{ type: 'autogenerated', dirName: 'eigencloud' }],
  eigencomputeSidebar: [{ type: 'autogenerated', dirName: 'eigencompute' }],
  eigenaiSidebar: [{ type: 'autogenerated', dirName: 'eigenai' }],
  eigenlayerSidebar: [{ type: 'autogenerated', dirName: 'eigenlayer' }],
  eigendaSidebar: [{ type: 'autogenerated', dirName: 'eigenda' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
*/
};


module.exports = sidebars;

/**
const sidebars = {
  productsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products',
      collapsible: false,
    },
  ],

  eigencloudSidebar: [
    {
      type: 'autogenerated',
      dirName: 'eigencloud',
      collapsed: false,
    },
  ],

  eigencomputeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'eigencompute',
      collapsed: false,
    },
  ],

  eigenaiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'eigenai',
      collapsed: false,
    },
  ],

  eigenlayerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'eigenlayer',
      collapsed: false,
    },
  ],

  eigendaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'eigenda',
      collapsed: false,
    },
  ],
};

module.exports = sidebars; */
